# Feb is in EST. Add 5h for UTC, which may also need an increase in the date.

# TODO: Define Zoom links once

# All weekend

[[events]]
datetime = 2023-02-25T01:30:00Z
title = 'Yahtzee Leaderboard'
desc = 'Our Yahtzee contest runs all weekend. See if you can make the highest score.'
howto = '''To be eligible for a prize, players must register with Givers &amp; Gamers. Details are available on
    <a href="/src/leaderboard/">our leaderboard page</a>.'''
all_weekend = true

[[events]]
datetime = 2023-02-25T01:30:00Z
title = 'PlayStation 5 raffle'
desc = ''
howto = '''Purchase a chance to win a PlayStation 5 console.
       Visit <a href="rmhcbluegrass.org/rmhcps5">rmhcbluegrass.org/rmhcps5</a>
       to enter.'''
all_weekend = true


# Day 1

[[events]]
datetime = 2023-02-24T23:30:00Z
title    = 'RMHC Staff Trivia'
desc     = 'Find out which RMHC Staffer knows the most about the House and its mission.'
Twitch   = true

[[events]]
datetime = 2023-02-25T01:30:00Z
title = 'Dungeons &amp; Dragons: Arena of Generosity'
desc = '''Adventurers must use their weapons, wizardry and wits to
        survive this gladitorial spectacle. Viewers will be called upon
        to help tip the odds in the adventurers' favor.'''
howto = '''Top fundraisers are eligible to play. Contact donald@kyfrieddice.com if interested.
        Visit <a href="https://roll20.net/">Roll20</a> to create an account,
        and return at game time to play. Game is limited to 5 players.'''
highlight = true
Twitch = true


# Day 2

[[events]]
datetime = 2023-02-25T16:00:00Z
title = 'Learn to Play: Yahtzee'
desc = '''Join an experienced player
          <a href="https://us02web.zoom.us/j/89052836552?pwd=ajJLV2pZcStOQmt1QVAwSEtYQ2RFQT09">on a Zoom call</a>, where
          you'll learn or refresh the rules while playing a non-competitive game.'''

[[events]]
datetime  = 2023-02-25T18:00:00Z
title     = 'Dungeons & Dragons: &sstarf;&bigstar;<em>Celebrity Edition</em>&bigstar;&sstarf;'
desc      = 'Activate your donor network to help our celebrity players serve those in need.'
highlight = true
Twitch    = true

[[events]]
datetime = 2023-02-25T22:00:00Z
title    = 'Golf With Your Friends Invitational'
desc     = 'Watch our streamer guests do their best on some increasingly difficult miniature golf holes.'
Twitch   = true

[[events]]
datetime = 2023-02-26T01:00:00Z
title = 'Countdown Trivia'
desc = 'A single-elimination, last contestant standing trivia showdown.'
howto = '''Advance registration is required. Questions are answered in a browser on your touchscreen device.
               You'll receive a URL just before the contest begins.'''
Twitch = true

[[events]]
datetime = 2023-02-26T03:30:00Z
title = 'Codenames'
desc = 'Spymasters must help their team discover the right cards using single-word clues.'
howto = '''Game begins after trivia concludes. Play online at <a href="https://codenames.game/">codenames.game</a>
       with the "room code" shown on the Twitch stream. Join us
       <a href="https://us02web.zoom.us/j/89307947726?pwd=eHQvWE9qcGF0SWUvMmJ1UFFxWjdFUT09">on Zoom</a>
       to discuss the clues.'''
Twitch = true


# Day 3

[[events]]
datetime = 2023-02-26T03:30:00Z
title = 'Codenames'
desc = 'Spymasters must help their team discover the right cards using single-word clues.'
howto = '''Game begins after trivia concludes. Play online at <a href="https://codenames.game/">codenames.game</a>
       with the "room code" shown on the Twitch stream. Join us
       <a href="https://us02web.zoom.us/j/89307947726?pwd=eHQvWE9qcGF0SWUvMmJ1UFFxWjdFUT09">on Zoom</a>
       to discuss the clues.'''
Twitch = true


# <section class="schedule">
#   <div class="day vertext">Day 3</div>
#   <div class="events">

#     <article id="202202201300" class="event">
#       <div class="when">
#         <p>1pm</p>
#         <p class="footnote">
#           <i class="fa-solid fa-mobile-alt fa-sm"></i>
#           <img alt="Zoom" title="Zoom" src="/images/logo-Zoom-300.png" />
#         </p>
#       </div>
#       <div class="what">
#         <p class="title">Family-friendly Jackbox</p>
#         <p class="howto">
#           Visit <a href="https://jackbox.tv">jackbox.tv</a>, and enter the
#           "room code" shown on the Twitch stream. Join the silliness
#           <a href="https://us02web.zoom.us/j/88168393635?pwd=YWJDaVBJdmtLVDdUUlM4VmtvQjhTUT09">on Zoom</a>.
#         </p>
#       </div>
#       <div class="watch">
#         <a href="https://bit.ly/twitchrmhc">
#           <img alt="link to Twitch" title="KFD on Twitch" src="/images/logo-Twitch-250.png" />
#         </a>
#       </div>
#     </article>

#     <article id="202202201530" class="event">
#       <div class="when">
#         <p>3:30pm</p>
#         <p class="footnote">
#           <i class="fa-solid fa-user-plus fa-sm"></i>
#           <img alt="Zoom" title="Zoom" src="/images/logo-Zoom-300.png" />
#         </p>
#       </div>
#       <div class="what">
#         <p class="title">Fall Guys</p>
#         <p class="desc">
#           Hordes of contestants make a wild dash through round after round of escalating chaos until one victor remains.
#         </p>
#         <p class="howto">
#           Fall Guys: Ultimate Knockout is available as a one-time purchase (currently $20) for computer
#           <a href="https://store.steampowered.com/app/1097150/Fall_Guys_Ultimate_Knockout/">via Steam</a>
#           or through the <a href="https://www.playstation.com/en-us/games/fall-guys-ultimate-knockout/">PlayStation Store</a>
#           for PS4 and PS5. (Speaking of PS5, have you heard about our <a href="rmhcbluegrass.org/rmhcps5">raffle</a>?)
#         </p>
#         <p class="howto">
#           Share in the chaos
#           <a href="https://us02web.zoom.us/j/88207189904?pwd=bVkwdWFTakZlYlJIcmd4UlFhU0xldz09">on Zoom</a>.
#         </p>
#       </div>
#       <div class="watch">
#         <a href="https://bit.ly/twitchrmhc">
#           <img alt="link to Twitch" title="KFD on Twitch" src="/images/logo-Twitch-250.png" />
#         </a>
#       </div>
#     </article>

#     <article id="202202201700" class="event highlight1">
#       <div class="when">
#         <p>5pm</p>
#       </div>
#       <div class="what">
#         <p class="title">Closing Ceremony, Raffle Drawing &amp; Awards</p>
#         <p class="desc">
#           We'll recognize our fundraising stars and
#           prize winners while celebrating our fundraising total.
#         </p>
#       </div>
#       <div class="watch">
#         <a href="https://bit.ly/twitchrmhc">
#           <img alt="link to Twitch" title="KFD on Twitch" src="/images/logo-Twitch-250.png" />
#         </a>
#       </div>
#     </article>
#   </div>
# </section>
